### ISSUE TITLE
subpad's begin_x begin_y are not relative to parent pad after refresh

### ISSUE THREAD

**Issue by Karolis-Sakavicius** [ruby/curses#23]
It seems like that subpad's begin_x and begin_y coordinates aren't relative to the parent pad but relative to the terminal screen if parent pad has been put on the screen using `refresh`. Not sure if it's the intended behavior. This example raises exception (failed to create window):
```
pad = Curses::Pad.new(2, 2)
pad.refresh(0, 0, 1, 1, 1, 1)
sub = pad.subpad(1, 1, 0, 0)
```

And this one works & looks the same on the screen - subpad is at (1, 1) in the terminal window and at (0, 0) relatively from parent pad.
```
pad = Curses::Pad.new(2, 2)
pad.refresh(0, 0, 1, 1, 1, 1)
sub = pad.subpad(1, 1, 1, 1)
```

This one works too and looks the same (refresh after pad & subpad creation):
```
pad = Curses::Pad.new(2, 2)
sub = pad.subpad(1, 1, 0, 0)
pad.refresh(0, 0, 1, 1, 1, 1)
```

It makes it difficult to create new subpads if parent pad is currently displayed on the screen, as you must know where it resides, making new subpad behave similarly to subwin. You can't put new subpad using relative coordinates to parent pad. Maybe I'm using it in a wrong way?

**Comment by shugo** [comment]
@drbrain Do you remember why subpad(3) was not used in your original patch?

  https://bugs.ruby-lang.org/issues/4896

**Comment by drbrain** [comment]
I imagine it was because I missed seeing the documentation for `subpad(3)`

**Comment by shugo** [comment]
@drbrain 
> I imagine it was because I missed seeing the documentation for subpad(3)

Thanks for your reply.
This is a breaking change, but I've fixed Pad#subpad to use subpad(3).

@Karolis-Sakavicius Could you try with master?

**Comment by drbrain** [comment]
I would say it fixes a bug, we should have used `subpad(3)` from the start.

**Comment by Karolis-Sakavicius** [comment]
Wow, that was quick!

@shugo it seems like I'm still having the same problem. This code still raises the same exception:
```
require 'curses'

pad = Curses::Pad.new(2, 2)
pad.refresh(0, 0, 1, 1, 1, 1)
sub = pad.subpad(1, 1, 0, 0)
```

and this one works:
```
require 'curses'

pad = Curses::Pad.new(2, 2)
pad.refresh(0, 0, 1, 1, 1, 1)
sub = pad.subpad(1, 1, 1, 1)
```

after rebuilding the gem from master.

**Comment by shugo** [comment]
> @shugo it seems like I'm still having the same problem. 

I made a wrong commit by a9300025, and it broke the fix:(
I hope it has been fixed by faf4ad1.

Could you try the HEAD of master again?

I tested the following code:

```
$ ruby -r ./curses.so -e 'pad = Curses::Pad.new(2,2); pad.refresh(0,0,1,1,1,1); sub = pad.subpad(1,1,1,1); sub.getch'
```

**Comment by Karolis-Sakavicius** [comment]
@shugo sorry for the delay - had a very busy day yesterday. Now it works fine, though I found some interesting behavior. If I put subpad into parent pad and refresh parent, everything's fine - subpad is placed inside the parent & subpad's coordinates are relative to the parent. But if I try to refresh the subpad, it behaves the same as regular Pad - coordinates, supplied in `refresh`, are not relative to parent but relative to the screen. I made this example to illustrate this:
```
require 'curses'
include Curses

init_screen
start_color

pad = Curses::Pad.new(4, 4)
pad.refresh(0, 0, 2, 2, 6, 6)

sub = pad.subpad(3, 3, 0, 0)

3.times do |line|
  sub.setpos(line, 0)
  sub << line.to_s * 3
end

refresh

sub.refresh(0, 0, 0, 0, 3, 3)

getch
```
here after `sub.refresh` subpad is placed at (0, 0) on the screen, not at (1, 1), where its parent belongs. Is that a correct behavior?

**Comment by shugo** [comment]
> here after `sub.refresh` subpad is placed at (0, 0) on the screen, not at (1, 1), where its parent belongs. Is that a correct behavior?

The following C code has the same behavior.

```c
#include <stdio.h>
#include <curses.h>

int
main()
{
    WINDOW *pad, *sub;
    int i;
    char s[4];

    initscr();
    start_color();
    pad = newpad(4, 4);
    prefresh(pad, 0, 0, 2, 2, 6, 6);
    sub = subpad(pad, 3, 3, 0, 0);
    for (i = 0; i < 3; i++) {
	snprintf(s, sizeof(s), "%d%d%d", i, i, i);
	wmove(sub, i, 0);
	waddstr(sub, s);
    }
    refresh();
    prefresh(sub, 0, 0, 0, 0, 3, 3);
    getch();
    endwin();
    return 0;
}
```

I guess you need to call `pad.refresh(0, 0, 2, 2, 6, 6)` instead of `sub.refresh(0, 0, 0, 0, 3, 3)`.

**Comment by Karolis-Sakavicius** [comment]
Got it. I was wondering if I could have a pad within a pad (nested pads), retaining all scrolling functionality of the subpad. Appearently subpad doesn't work that way - it acts more like a window within a pad.

Thank you very much for your effort, @shugo!
